src/models.py
from . import db
from sqlalchemy import Column, Integer, String

# Create the User model to represent the users table
class User(db.Model):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    username = Column(String, nullable=False, unique=True)
    name = Column(String, nullable=False)
    password = Column(String, nullable=False)

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.exc import OperationalError

db = SQLAlchemy()

# Configuration of the database
DB_USER = 'postgres'
DB_PASSWORD = ''
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_NAME = 'USER_MANAGEMENT'

URI = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# Create the function to create the app
def create_app():
    app = Flask(__name__)

    # Initialize the application with the SQLAlchemy instance
    app.config['SQLALCHEMY_DATABASE_URI'] = URI
    app.config['SECRET_KEY'] = 'dtnls2024'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    try:
        db.init_app(app)
        with app.app_context():
            db.create_all()  # This line will attempt to connect to the database
    except OperationalError:
        print("Could not connect to the database. Please ensure your database service is running and the URI is correct.")


    # Import the routes
    from .routes import routes

    app.register_blueprint(routes, url_prefix='/')

    return app

src/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from sqlalchemy import and_
from . import db
from .models import User

routes = Blueprint('routes', __name__)

# Create the home route
@routes.route('/')
def home():

    users = User.query.all()

    # Transform the data into dicts
    user_dicts_ls = [user.__dict__ for user in users]

    return render_template("index.html", data=user_dicts_ls)

@routes.route('/new', methods=['POST'])
def add_user():

    username = request.form['username']
    name = request.form['name']
    password = request.form['password']

    # Validate user information and handle errors gracefully
    errors = []
    if not username:
        errors.append('Username is required.')
    if not name:
        errors.append('Name is required.')
    if not password:
        errors.append('Password is required.')

    if errors:
        for error in errors:
            flash(error, category='error')
            return redirect(url_for('routes.home'))

    # Validate if a user with the username already exists
    existing_user = User.query.filter_by(username=username).first()

    if existing_user is not None:
        flash('Username already registered!', category='error')
        return redirect(url_for('routes.home'))
    else:
        new_user = User(username=username, name=name, password=password)
        db.session.add(new_user)
        db.session.commit()
        flash('User successfully added!', category='success')
        return redirect(url_for('routes.home'))


@routes.route('/edit/<string:id>')
def edit_user(id):

    user = User.query.get(id)
    return render_template('update.html', user=user)


@routes.route('/update/<string:id>', methods=['POST'])
def update_user(id):

    user = User.query.get(id)

    # Validate if a user with the username already exists and if the fields are filled
    if user:
        username = request.form['username']
        name = request.form['name']
        password = request.form['password']
        existing_username = User.query.filter(and_(User.username == username, User.id != id)).first()
        if existing_username:
            flash('Username already registered!', category='error')
            return redirect(url_for('routes.edit_user', id=id))
        elif not username or not name or not password:
            flash('All fields must be filled!', category='error')
            return redirect(url_for('routes.edit_user', id=id))
        user.username = username
        user.name = name
        user.password = password
        db.session.commit()
        flash('User successfully updated!', category='success')
        return redirect(url_for('routes.home'))



@routes.route('/delete/<string:id>')
def delete_user(id):

    user = User.query.get(id)
    if user:
        db.session.delete(user)
        db.session.commit()
        flash('User successfully deleted!', category='success')
    return redirect(url_for('routes.home'))

src/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>
<body>

  <h1 class="text-center mt-5 mb-5 text-primary">Python-PostgreSQL</h1>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

  <div class="container">
    {% block content %}{% endblock %}
  </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
</body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="card shadow">
    <div class="card-body">
        <form action="/new" method="POST">
            <div class="row mb-3">
                <div class="col">
                    <label>Username</label>
                    <input type="text" class="form-control mb-3" name="username">
                </div>
                <div class="col">
                    <label>Name</label>
                    <input type="text" class="form-control mb-3" name="name">
                </div>
                <div class="col">
                    <label>Password</label>
                    <input type="text" class="form-control mb-3" name="password">
                </div>
                <div class="col">
                    <button class="btn btn-primary mb-3 mt-4" type="submit">Save</button>
                </div>
            </div>
        </form>


        <!-- Tabla -->

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Username</th>
                    <th scope="col">Name</th>
                    <th scope="col">Password</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
        
        <tbody>
            {% for d in data %}
                <tr>
                    <td>{{d.id}}</td>
                    <td>{{d.username}}</td>
                    <td>{{d.name}}</td>
                    <td>{{d.password}}</td>
                    <td><a href="{{url_for('routes.edit_user', id=d.id)}}" class="btn btn-primary btn-sm" id="btn-edit{{d.id}}">Edit</a></td>
                    <td><a href="{{url_for('routes.delete_user', id=d.id)}}" class="btn btn-danger btn-sm">Delete</a></td>
                </tr>



            {% endfor %}

        </tbody>

    </table>


    </div>
</div>
{% endblock %}

src/templates/update.html
{% extends "base.html" %}
{% block content %}

<div class="card shadow">
    <div class="card-body">
        <form action="/update/{{user.id}}" method="POST">
            <div class="row mb-3">
                <div class="col">
                    <label>Username</label>
                    <input type="text" class="form-control mb-3" name="username" value="{{user.username}}">
                </div>
                <div class="col">
                    <label>Name</label>
                    <input type="text" class="form-control mb-3" name="name" value="{{user.name}}">
                </div>
                <div class="col">
                    <label>Password</label>
                    <input type="text" class="form-control mb-3" name="password" value="{{user.password}}">
                </div>
                <div class="col">
                    <button class="btn btn-primary mb-3 mt-4" type="submit">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}